# NODE-RED
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dt-1
  template:
    metadata:
      labels:
        app: dt-1
    spec:
      hostname: dthphwproto  # must match to the OPC-UA TLS certificate altname within the container
      containers:
        - name: dt-1
          image: ampandroa/datadrivendigitaltwin:12.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: nodered
              containerPort: 1880   # Node-RED HTTPS port
              hostPort: 1880 #Map to host port for external access
            - name: opcua
              containerPort: 4840   # OPC-UA port
              hostPort: 4880 #Map to host port for external access
---

# LoadBalancer Service to expose dt-1 publicly
apiVersion: v1
kind: Service
metadata:
  name: dt-core
spec:
  type: ClusterIP  
  selector:
    app: dt-1
  ports:
    - name: nodered
      port: 1880        # internal cluster port
      targetPort: 1880  # container port
    - name: opcua
      port: 4840        # internal cluster port
      targetPort: 4840  # container port
---

# PHPMYADMIN + MARIADB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: "db"
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: ClusterIP    # local access ONLY: sudo k8s kubectl port-forward svc/phpmyadmin 8080:80
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: andringitra/dt-mariadbencrypted:2.0
          env:
            - name: MYSQL_USER
              value: "prototype"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: prototype-password
            - name: MYSQL_DATABASE
              value: "DTHPHW_BACKUP"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root-password
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc

---
# Service for MariaDB database
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306

---
# Persistent Volume Claim for MariaDB storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Increased storage for failover and replication support

---
# Secrets for MariaDB root and user passwords
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  root-password: WWFubmljaw==          # Root password
  prototype-password: WWFubmljaw==     # Password for the 'prototype'' user
